### ISSUE TITLE
Get email from b.p.o passing DMARC (etc)

### ISSUE THREAD

**Issue by ncoghlan** [python/bugs.python.org#10]
As discussed at http://psf.upfronthosting.co.za/roundup/meta/issue562, bugs.python.org has recurring problems with its messages getting marked as spam for some users. I think it only works for me because I listed bugs.python.org as an approved sender years ago, since the message headers include:

    Authentication-Results: mx.google.com;
       spf=neutral (google.com: 46.4.197.70 is neither permitted nor denied by best guess record for domain of roundup-admin@psf.upfronthosting.co.za) smtp.mailfrom=roundup-admin@psf.upfronthosting.co.za;
       dmarc=fail (p=NONE sp=NONE dis=NONE) header.from=python.org

I suspect this may be resolved by the b.p.o server rehosting project that @soltysh and @ewdurbin are working on, but if that isn't the case, another possibility may be to look into whether or not b.p.o can migrate to whichever mail sending solution that PyPI is now using.

**Comment by JulienPalard** [comment]
Can the dmarc=fail be due an alignment problem? I noticed the return-path and the from are different:

    Return-Path: [...]@roundup.psfhosted.org>
    From: [...]@bugs.python.org>

According to [rfc7489$B1.1](https://datatracker.ietf.org/doc/html/rfc7489#appendix-B.1.1) they need to be the same for SPF to be considered aligned.

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.
