### ISSUE TITLE
unable to register

### ISSUE THREAD

**Issue by james-stevens** [python/bugs.python.org#13]
I've tried to register at bugs.python.org, but it doesn't appear to work - id "james_r_c_stevens"

once registered I get the confirmation email and click the link, but the login doesn't work

if I try to login the screen refreshes sending me to "https://bugs.python.org/?%40error_message=Invalid+login" - buy no such error message ever appears. Apart from the screen-refreshing nothing else happens.

I can re-register as many times as I like with identical details.

**Comment by ezio-melotti** [comment]
I don't see anything unusual in the error logs.  On some mail clients the confirmation link is broken on two lines -- if that's the case you might have to put it back together, and if you do that incorrectly you might get an error.

**Comment by james-stevens** [comment]
not the issue I was getting - (see attached)

I tried the email reply method & clicking on the link method

I've registered twice, with the same details and gone through the same procedure. I've clicked the link multiple times.

Are you not seeing that in the logs?

![selection_2018-06-26_001](https://user-images.githubusercontent.com/30622954/41909115-1b948da8-793e-11e8-8870-48e924d9447a.png)

**Comment by james-stevens** [comment]
As you can see, then entire URL as click-through fine - but there is no confirmation and the login section is still asking me to login

![selection_2018-06-26_002](https://user-images.githubusercontent.com/30622954/41909206-5a2b2a4a-793e-11e8-892b-274b986502d9.png)

**Comment by ezio-melotti** [comment]
This is because the homepage URL entered when you registered is invalid.
See also http://psf.upfronthosting.co.za/roundup/meta/issue591
I would suggest to leave the "homepage" field empty when you register, and possibly fill it in later.

**Comment by james-stevens** [comment]
So

1)  this has been an issue for over a year and it's **still** not fixed (not even any warnings etc) - that's appalling -  I can give you a Javascript regex that will validate a URL if you like, you just put it in the "onSubmit" for the form.

2) you knew about this but didn't tell me the first time, but instead tried to claim it was something I was doing .... Mmmmm


James
