### ISSUE TITLE
SSL connection errors to bpo

### ISSUE THREAD

**Issue by Mariatta** [python/bugs.python.org#15]
We're seeing a number of errors when `ni` tries to connect to bpo to check for CLA.
These are logged in https://github.com/python/core-workflow/issues/259

```
Cannot connect to host bugs.python.org:443 ssl:None
[[SSL: BAD_SIGNATURE] bad signature (_ssl.c:1045)]
```

I wasn't sure who can look into this, figured I start here.
Thanks.

Here's the stacktrace:
![screen shot 2018-07-05 at 9 58 55 am](https://user-images.githubusercontent.com/5844587/42336962-2105bc82-803a-11e8-9521-75a5997ddeff.png)

**Comment by vstinner** [comment]
I reported the same issue a few months ago (Oct 2017) :-(

https://github.com/python/psf-infra-meta/issues/4

**Comment by Mariatta** [comment]
Thanks. I'll close this since it is tracked elsewhere.

**Comment by Mariatta** [comment]
Duplicate of python/psf-infra-meta#4
