### ISSUE TITLE
Update TLS version to 1.2 or even 1.3

### ISSUE THREAD

**Issue by genodeftest** [python/bugs.python.org#16]
TLS 1.0 and 1.1 are old and weak, they may be broken at some time soon. Some projects such as [Fedora](https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2) and [Debian](https://lists.debian.org/debian-devel/2017/08/msg00166.html) are thinking about disabling TLS versions below 1.2 by default. TLS 1.2 has been available for almost 10 years and TLS 1.3 is coming soon™.

Any server of the python project, including bugs.python.org, should support TLS 1.2 at least.

[SSLLabs report on bugs.python.org](https://www.ssllabs.com/ssltest/analyze.html?d=bugs.python.org)

Note: This bug has been reported on python/pythondotorg#1297 before and has been "moved" here.

**Comment by bitdancer** [comment]
There is an impending infrastructure migration that I believe will take
care of this issue.

**Comment by ewdurbin** [comment]
resolved
