### ISSUE TITLE
Rietveld patch review links return 404

### ISSUE THREAD

**Issue by tirkarthi** [python/bugs.python.org#18]
Rietveld links that contain review comments for patches now return 404. It used to work before. This is causing issues while looking up review comments to know why a decision was made. It was initially reported in Zulip but I am opening an issue here so that it can be tracked. It will be helpful that the comments on the patches are restored for reference on issues. Hope this is the right place for this. Feel free to close this if Rietveld issues are tracked in another place.

Initial report on Zulip : https://python.zulipchat.com/#narrow/stream/116501-workflow/topic/Rietveld
Sample link that returns 404 : https://bugs.python.org/review/13607/#ps3902 

Thanks

**Comment by ezio-melotti** [comment]
As I mentioned on Zulip, I'm not aware of any changes that might have broken it, perhaps @ewdurbin knows something about it?

**Comment by ewdurbin** [comment]
Resolved. Misconfiguration.
