### ISSUE TITLE
Query deletion is broken

### ISSUE THREAD

**Issue by swarmer** [python/bugs.python.org#20]
When I delete a query, it is still shown in Your Queries list on the sidebar, but it can't be modified and is not visible in `https://bugs.python.org/query?@template=edit` anymore.

Long story short, I now have a big mess of useless queries in my sidebar that I can't delete. If not a proper fix in code, I would appreciate if someone can delete or hide all my queries (`anton.barkovsky`).

**Comment by ezio-melotti** [comment]
See http://psf.upfronthosting.co.za/roundup/meta/issue352 
This seems to be fixed, but apparently the fix requires JS.
Do you have JS disabled?

**Comment by swarmer** [comment]
No, I don’t.
Also even if deletion was fixed for future deletions, my records are already corrupted.

**Comment by ezio-melotti** [comment]
Maybe @bitdancer can help, since he fixed the original issue.

**Comment by swarmer** [comment]
I selflessly sacrificed some more pixels on my sidebar, and on deleting another query, I couldn't see any errors in my browser's (Chrome 69) console.

**Comment by bitdancer** [comment]
On Thu, 11 Oct 2018 17:12:52 -0700, Ezio Melotti <notifications@github.com> wrote:
> Maybe @bitdancer can help, since he fixed the original issue.

My memory is a bit vague, but I believe this was fixed in the upstream
templates (by someone other than me, though starting from my original set
of changes, I think), so you could compare the bpo code against upstream.
If you toggle the query to "leave out" first you are fine...the problem
is in the logic of what gets included in the sidebar (it needs to filter for
retired or some other flag and currently isn't; I don't remember the details).

--David

**Comment by swarmer** [comment]
@bitdancer Hmm. If I was brave enough to try to fix this, I'd need to produce a patch to `https://hg.python.org/tracker/roundup/shortlog/bugs.python.org`, right? Where would I submit the patch?

**Comment by rouilj** [comment]
I think you are describing: https://issues.roundup-tracker.org/issue2550831

**Comment by berkerpeksag** [comment]
I've tried to fix this before: https://mail.python.org/pipermail/tracker-discuss/2016-June/004112.html @rouilj is https://sourceforge.net/p/roundup/code/ci/425b4c4fc345/ the commit that fixes this bug?

**Comment by berkerpeksag** [comment]
Pushed a fix that allows removing retired queries created by user from listing in "Your Queries". Feel free to suggest any improvements to the wording.

**Comment by rouilj** [comment]
In message <python/bugs.python.org/issues/20/667529713@github.com>,
Berker Peksag writes:
> I've tried to fix this before:
> https://mail.python.org/pipermail/tracker-discuss/2016-June/004112.html
> @rouilj is https://sourceforge.net/p/roundup/code/ci/425b4c4fc345/ the
> commit that fixes this bug?

Yes, but from the hg history it looks like c8bf4e9912ed and
1bd252244501 also changed
share/roundup/templates/classic/html/query.edit.html.

You might want to see if copying
share/roundup/templates/classic/html/query.edit.html from a 1.6.1
release over the existing query.edit.html does the trick.

I doubt it would be that easy but...

Also I handle the OP problem (retired query showing up in query
sidebar) a little differently I think.

If the user deletes/retires a query without unchecking "Include in
your queries", The query should show up in the "Active Retired..."
section. So the user can restore the query, uncheck the "Include in
your queries" checkbox submit the change. Then re-delete/retire the
query.

Then the query dissapears from the edit form.

So I think it does let the user address the problem but the workflow
could be better.
