### ISSUE TITLE
Invalid email in a profile causes server error and doesn't add comment

### ISSUE THREAD

**Issue by tirkarthi** [python/bugs.python.org#21]
When a user has an invalid email in their profile then while adding a comment in the issue to which they are subscribed tries to send an email to them. The invalid email causes failure which is not handled and I assumes it causes the transaction to rollback adding no comment to the issue but since other webhooks were triggered IRC is notified about the comment. Reporting this here in case someone stumbles upon this issue.

Relevant Zulip stream topic : https://python.zulipchat.com/#narrow/stream/116501-workflow/topic/Is.20adding.20comment.20in.20bpo.20broken.20for.20anyone.3F

cc: @ezio-melotti

**Comment by ezio-melotti** [comment]
I suspect this is a Roundup issue and should therefore be reported upstream, but I didn't have time to reproduce and investigate the issue yet.
We can keep this open as a reminder for now.

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.

cc @rouilj
