### ISSUE TITLE
User timezone setting in profile no longer affects web page output ?

### ISSUE THREAD

**Issue by ned-deily** [python/bugs.python.org#24]
I can't *swear* to it but I'm pretty sure that it used to be the case that the date and times displayed in individual b.p.o issue pages obeyed the Timezone setting in my b.p.o user profile (`Your Details`).  Recently I've noticed that times now appear to be unconditionally displayed in UTC for me when logged in.  I tried changing the timezone in my profile but that didn't seem to make a difference.  Perhaps something happened during the b.p.o server move?

**Comment by ned-deily** [comment]
@ewdurbin FYI

**Comment by ewdurbin** [comment]
@ned-deily sneaky conditional code in roundup that changes behavior based on `pytz` being installed... I've added that requirement and this feature appear to be working now :)

**Comment by ewdurbin** [comment]
ref: https://github.com/python/psf-salt/commit/9ab7213514ad02c1e10350ae1e40a210242d87a0

**Comment by ned-deily** [comment]
Thanks, @ewdurbin, for your, um, timely response!
