### ISSUE TITLE
Remove linked PR in bpo, if the bpo number was changed.

### ISSUE THREAD

**Issue by Mariatta** [python/bugs.python.org#25]
https://github.com/python/cpython/pull/11414 initially has bpo-35434 in the title, so the pull request was included in bpo-35434.
However the title was later changed to bpo-35431. However, the PR was still linked to bpo-35434.

It would be great if the previous link in bpo-35434 can be automatically removed.

**Comment by FR4NKESTI3N** [comment]
Sorry about that. Unlinked it.

**Comment by FR4NKESTI3N** [comment]
Sorry about that, I have removed the links in bpo-35434 manually. But yeah, automatic unlinking would be great in case someone else makes a typo.

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.
