### ISSUE TITLE
An error has occurred A problem was encountered processing your request. The tracker maintainers have been notified of the problem.

### ISSUE THREAD

**Issue by evandrocoan** [python/bugs.python.org#26]
I had and account a year ago, but now I tried to login it said to me the user was non-existent. Then I created a new account, and when I hit the confirmation button on my email it opened this page:

1. ![image](https://user-images.githubusercontent.com/5332158/50859465-90ee8780-137a-11e9-81f3-57f403f082c5.png)
   https://bugs.python.org/?@action=confrego&otk=OyAWQIJSDAX44wRQbkvReXqZf7qNNMFt

1. ![image](https://user-images.githubusercontent.com/5332158/50858750-73b8b980-1378-11e9-97b6-76779dea8fd2.png)

Did you get informed of the problem?

How can I report bugs?

**Comment by Mariatta** [comment]
It seems that you're able to create the account in bpo now, so you'll have to actually create the unittest bug there. Sorry for the trouble.
However, this is the appropriate place to report issues with the account creation itself.

**Comment by evandrocoan** [comment]
I am trying to log in, but it keeps telling me: 
1. broken form: multiple @action values submitted
   ![image](https://user-images.githubusercontent.com/5332158/50861019-a4035680-137e-11e9-93f1-5d6c1030ca56.png)

**Comment by evandrocoan** [comment]
I managed to login by directly accessing the page with this link:
1. https://bugs.python.org/

Before I was accessing the confirmation link:
1. https://bugs.python.org/?@action=confrego&otk=OyAWQIJSDAX44wRQbkvReXqZf7qNNMFt

And trying to login from that page:
![image](https://user-images.githubusercontent.com/5332158/50861145-fb092b80-137e-11e9-9990-6f687d44b90d.png)

Then, it was saying this bug:
![image](https://user-images.githubusercontent.com/5332158/50861019-a4035680-137e-11e9-93f1-5d6c1030ca56.png)

**Comment by Mariatta** [comment]
Perhaps @ewdurbin or @ezio-melotti can take a look. I don't have access to the logs.

**Comment by ewdurbin** [comment]
The issue appears to be a database constraint:

```
IntegrityError: duplicate key value violates unique constraint "_user_key_retired_idx" DETAIL: Key (__retired__, _username)=(0, addons_zz) already exists.
```

So it appears that multiple registration attempts with the same username `addons_zz` were initiated, and at least one was completed.

**Comment by ewdurbin** [comment]
So that at least explains the first issue, combined with the other referenced issue it appears that between the two email addresses @evandrocoan tried to use, one of them was successful in creating a n account.

When the user clicked the confirmation link for a second time, the OTK tried to create an account with the same user name, and obliterated the one time use key. @evandrocoan do you have an error message or screenshot for what that looked like?

**Comment by ewdurbin** [comment]
I'm able to reproduce the `multiple @action values submitted` error by going to `https://bugs.python.org/?@action=foo`, receiving an `No such action "foo"` error, then trying to log in.

Will look into if there's away to strip the outer `@action` from the POST used to log in, but I'm not sure it will be that simple.

**Comment by evandrocoan** [comment]
> @evandrocoan do you have an error message or screenshot for what that looked like?

I have posted on this thread all screenshots I got. I think what you want now, would be this screenshot:

![image](https://user-images.githubusercontent.com/5332158/50858750-73b8b980-1378-11e9-97b6-76779dea8fd2.png)

**Comment by rouilj** [comment]
For the double @action issue, See:
'''
changeset:   5294:3e740c65510e
user:        John Rouillard <rouilj@ieee.org>
date:        Thu Sep 28 16:48:52 2017 -0400
files:       website/issues/html/page.html
description:
Fix double @action failure when you do a full text search and then
attempt to show an issue. The original action="#" included the searches
@action in the url and the show issue included another @action=show.
'''
in the upstream repo: https://sourceforge.net/p/roundup/code/ci/3e740c65510e

**Comment by eli-fin** [comment]
Ran into this issue (logged in with github once, but my email wasn't public, made it public and tried again, got this error).
Is there something I can do about it? Maybe like a manual step?

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.
