### ISSUE TITLE
It is not sending me the confirmation email if I use my email from @hotmail.com, If I use my email from @outlook.com, the confirmation was sent immediately

### ISSUE THREAD

**Issue by evandrocoan** [python/bugs.python.org#27]
Continuation from: 
1. https://github.com/python/bugs.python.org/issues/26 An error has occurred A problem was encountered processing your request. The tracker maintainers have been notified of the problem.

On that issue, I received the confirmation email because I used my email from @outlook.com, but I am still waiting the confirmation email for my email from @hotmail.com

No, it is not on my spam directory. There is nothing on my spam directory:
![image](https://user-images.githubusercontent.com/5332158/50859868-a87a4000-137b-11e9-907b-34eeae3ea781.png)

**Comment by evandrocoan** [comment]
I just received the email for my @hotmail.com email, several hours after the @outlook.com, and I tried to access the link, it said invalid page. Anyways, I do not need another account, I already got the one from the @outlook.com email.

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.
