### ISSUE TITLE
Changes to issues result in new noticeable delays for the web page to update.

### ISSUE THREAD

**Issue by ned-deily** [python/bugs.python.org#29]
See discussion at https://discuss.python.org/t/bugs-python-org-slowing-down/850/.  My guess is that something changed when the server was moved.  If you bring up the #python-dev IRC channels, the updates there appear much faster than on the web browser.  This didn't used to be the case and the delay is long enough to be annoying.

@ewdurbin

**Comment by ewdurbin** [comment]
This appears to be related to the speed of sending emails over SMTP.

Previously there was a local postfix instance handling outbound emails, so connection/submission/confirmation for each email to send was minimal. On an issue that will notify N participants, the request will take O(N) longer than before to send all the emails.

I’ll look into configuring the postfix that’s configured for inbound currently to act as a proxy for outbound.

**Comment by ewdurbin** [comment]
Confirmed and have a working solution. Will implement it this evening.

**Comment by ewdurbin** [comment]
This is resolved. I thought I had a meeting that I don't have :)

**Comment by ned-deily** [comment]
Thanks, @ewdurbin!
