### ISSUE TITLE
Add "release-blocker" autonosy entry for 3.8 release manager

### ISSUE THREAD

**Issue by ned-deily** [python/bugs.python.org#31]
b.p.o knows to _autonosy_ a release's release manager when an issue's priority is set to **release-blocker**.  The 3.8 release manager, @ambv, needs to be added.

It looks like the required change (untested!) to https://hg.python.org/tracker/python-dev is:
```
diff --git a/detectors/autonosy.py b/detectors/autonosy.py
--- a/detectors/autonosy.py
+++ b/detectors/autonosy.py
@@ -14,6 +14,7 @@
     'Python 3.5': '2731', # larry
     'Python 3.6': '5248', # ned.deily
     'Python 3.7': '5248', # ned.deily
+    'Python 3.8': '12704',  # lukasz.langa
 }

 def autonosy(db, cl, nodeid, newvalues):
```

**Comment by ewdurbin** [comment]
I should update the hg.python.org repo to note that tracker configs have moved to https://bitbucket.org/account/user/python/projects/BPO...

Anywho, this is done and will be picked up on next run of salt. https://bitbucket.org/python/tracker-cpython/commits/865bd3d5b2b496c213eb2e3acaaaaf3018a0b1a7

**Comment by ned-deily** [comment]
Thanks!  FYI, I found the references to hg.python.org in https://wiki.python.org/moin/TrackerDevelopment (which is linked to from the bugs.python.org sidebar) and in https://github.com/python/docker-bpo README.md

**Comment by ewdurbin** [comment]
Thank you for the references! I'll get those updated.
