### ISSUE TITLE
Cannot open nosy list

### ISSUE THREAD

**Issue by andresdelfino** [python/bugs.python.org#32]
When clicking "list" on a bug to check the list of experts, I see this: https://imgur.com/a/Ttk04vW Same happens on Firefox.

On Zulip (https://python.zulipchat.com/#narrow/stream/174027-general.2Fhelp/topic/Unable.20to.20use.20nosy.20list.20on.20bpo/near/160231750), SilentGhost commented :

> Yeah, I get the following errors in console (one per frame):
> 
> Load denied by X-Frame-Options: https://bugs.python.org/user?@template=help-empty&@startwith=0&properties=username,realname,address&property=nosy&form=itemSynopsis&type=checkbox&@sort=username&@pagesize=50 does not permit framing.

**Comment by terryjreedy** [comment]
The imgur link gives a blank image.  A description is more permanent and reliable.

What I see on Windows/Firefox is a popup window titled Nosy help with this url:
https://bugs.python.org/user?@startwith=0&@template=help&properties=username,realname,address&property=nosy&form=itemSynopsis&type=checkbox&@sort=username&@pagesize=50
This url searches registered bpo users.  I am not sure what it is meant to do.  It does not display the experts list in the devguide.

The content of the popup is a stack of three blank read-only boxes, medium, tall, and short in height.

**Comment by Mariatta** [comment]
Confirming that it doesn't seem to work.

This is the popup I'm seeing:

![Screen Shot 2019-03-12 at 3 35 55 PM](https://user-images.githubusercontent.com/5844587/54240863-8cf6f700-44dc-11e9-8099-72d7a5a016d4.png)

**Comment by andresdelfino** [comment]
Tried to test this again to see if the issue can be closed, but I don't see any "list" button. Perhaps that UI was removed?

**Comment by berkerpeksag** [comment]
Correct, the list popup has been removed in https://github.com/psf/bpo-tracker-cpython/commit/c0540d007120ba5a2b8c740941cc920e968bfcfd.

**Comment by andresdelfino** [comment]
@berkerpeksag thanks!
