### ISSUE TITLE
Add Auto Import extension for Python for VS Code

### ISSUE THREAD

**Issue by ashwanidv100** [python/bugs.python.org#33]
I think there is many auto import extension, but not for Python, which is very extensive for work with VS Code. I am sorry if this feature is already suggested, but like to contribute if it is in development. Please do share some info. if this is already resolved, and I didn't find any other place to report this.

**Comment by Mariatta** [comment]
This tracker is for issues related to the bugs.python.org issue tracker, not for Python for VS code.
I think this is the repo for Python VS code extension https://github.com/Microsoft/vscode-python.
Thanks.

**Comment by ashwanidv100** [comment]
Thanks Mariatta, to share the link !
