### ISSUE TITLE
Crash bug under python 3 in https://hg.python.org/tracker/python-dev/file/tip/extensions/timestamp.py

### ISSUE THREAD

**Issue by rouilj** [python/bugs.python.org#37]
I use this bit of code in my own tracker:
https://hg.python.org/tracker/python-dev/file/tip/extensions/timestamp.py#l6
This crashes under python 3 with the latest roundup because time.time() returns
a float and not an int.

Under python2, this code works. But it does not work under python 3.
E.G.
```
Python 3.4.3 (default, Nov 12 2018, 22:25:49)
>>> import time
>>> import struct
>>> struct.pack("i", time.time())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: required argument is not an integer
```

Changing "i" to "f" seems to fix the issue in python3 and is backwards compatible to python 2.

This is not an issue on bugs.python.org currently as it is running python2 and I assume
python2 is converting time.time() into an int as https://docs.python.org/2/library/time.html says:

```
 time.time()
    Return the time in seconds since the epoch as a floating point number. ...
```

However if you want to upgrade to the next release of roundup, this will need to be fixed.

(Also is this int/float conversion a bug in python2 or in python 3?)

-- rouilj

**Comment by rouilj** [comment]
It turns out that a couple of other string/byte conversions are needed if you are running this
code under python 3. This code will only work with the newest roundup that supports python3:

```
# from https://hg.python.org/tracker/python-dev/rev/83477f735132
# stop registration on web if it's too fast.
import time, struct, base64
from roundup.cgi.actions import RegisterAction
from roundup.cgi.exceptions import *
from roundup.anypy.strings import s2b, b2s

def timestamp():
    return b2s(base64.encodebytes(struct.pack("f", time.time())).strip())

def unpack_timestamp(s):
    return struct.unpack("f",base64.decodebytes(s2b(s)))[0]

class Timestamped:
    def check(self):
        try:
            created = unpack_timestamp(self.form['opaque'].value)
        except (KeyError, struct.error):
            raise FormError("somebody tampered with the form")
        if time.time() - created < 4:
            raise FormError("responding to the form too quickly")
        return True

class TimestampedRegister(Timestamped, RegisterAction):
    def permission(self):
        self.check()
        RegisterAction.permission(self)

def init(instance):
    instance.registerUtil('timestamp', timestamp)
    instance.registerAction('register', TimestampedRegister)
```

-- rouilj

**Comment by berkerpeksag** [comment]
Thank you for the heads up! I doubt we are gong to run bugs.p.o on Python 3 anytime soon and even if we want to do that, we'd need more changes than just the ones in the timestamp extension. I'll go ahead and close it for now.
