### ISSUE TITLE
New user confirmation email abuse

### ISSUE THREAD

**Issue by omicron-b** [python/bugs.python.org#39]
**Describe the bug**
Spammers create a new user with spam instead of username, really long string including emojis.
As a result, anyone receives spam from legitimate email as a registration confirmation.

**To Reproduce**
I did not try to reproduce the issue.

**Expected behavior**
Username string should be limited in length and characters.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/32303844/71584055-ee8a5f80-2b08-11ea-8def-9350fbeb3b93.png)

**Desktop (please complete the following information):**
No information

**Additional context**
Here is what I believe is the username string:
```
✅✅✅ ВАМ пришло  134 150₽ 🎁 Пожалуйста оформите на сайте 👉👉👉  http://www@PY.stepan2017.ru/py ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋ ⚋
```

**Comment by rouilj** [comment]
Take a look at: https://rouilj.dynamic-dns.net/fossil/roundup_sysadmin/artifact/b846879c85b5bbd1 . The userauditor.py includes:

```
valid_username = re.compile('^[a-z0-9_@!%.-]+$', re.IGNORECASE)
```

in the module and adds:

```
   if 'username' in newvalues:
       logging.debug("processing username: %s", newvalues['username'])
       if not valid_username.match(newvalues['username']):
           raise ValueError, "Username/Login Name must consist only of the letters a-z (any case), digits 0-9 and the symbols: @._-!%"

```
inside  audit_user_fields(). The regexp may need to be changed to match alphabetic in different languages (maybe \w). Length limitation can be had by replacing '+' with {1,20} for example.

While this doesn't prevent somebody from making the garbage request, it will reject an attempt to create it and if you are running in "INSTANT_REGISTRATION" mode, it should prevent the registration.

To reject the registration replace the 'edit' action by creating a new action as described
in: http://roundup-tracker.org/docs/customizing.html#defining-new-web-actions

Have the new action inherit from cgi.actions RegisterAction. Parsing the form using:

```
props, links = self.client.parsePropsFromForm(create=1)
```

and verify the value of the username (I think) form prop before passing it to the handler method
of RegisterAction to do all the actual registration bits.

An example replacing the edit action can be found at: 

  https://rouilj.dynamic-dns.net/fossil/roundup_sysadmin/artifact/948454fcbf988386

at least I think this should work if you need to block the registration attempt.

**Comment by berkerpeksag** [comment]
https://github.com/psf/bpo-tracker-cpython/commit/0136a274640680d8109fe86b013007627093de4c should mostly prevent cases showed in the original message. We can always tweak the validation rules to be more strict.
