### ISSUE TITLE
Archive the legacy setuptools issue tracker

### ISSUE THREAD

**Issue by ncoghlan** [python/bugs.python.org#4]
The setuptools issue tracker migrated to GitHub a while back, but https://bugs.python.org/setuptools/ doesn't indicate that.

https://hg.python.org/tracker/setuptools/ should be archived somehow, and update to redirect anyone attempting to use it to https://github.com/pypa/setuptools/issues

**Comment by berkerpeksag** [comment]
https://bugs.python.org/setuptools/ gives me 404 and I don't think it's possible to archive a repository (or something similar) in hgweb. I'll just go ahead and close this issue :)
