### ISSUE TITLE
Please add new categories in the bug tracker

### ISSUE THREAD

**Issue by vstinner** [python/bugs.python.org#40]
Hi,

Would it be possible to add the a "C API" category to the bug tracker? It's surprising to not have the category in the bug tracker, since we have the category in blurb for NEWS entries.

Victor

**Comment by rouilj** [comment]
Vstinner, do you know who is supposed to ok requests like this? Adding it should be trivial.

**Comment by berkerpeksag** [comment]
It looks like the C API component has already been added:

![image](https://user-images.githubusercontent.com/26338/89089002-cff08d80-d3a3-11ea-9a37-9766aebfe3d8.png)

Please reopen this or create a new issue if you want to add another component.
