### ISSUE TITLE
Login via Google doesn't work

### ISSUE THREAD

**Issue by vstinner** [python/bugs.python.org#41]
@isidentical wrote at https://github.com/python/cpython/pull/17612#issuecomment-566184381 :

> Yes but currently I can only reply through mail because bpo logins with
> google doesnt work. And if needed I can implement this lazy loading idea i
> proposed earlier.

**Comment by isidentical** [comment]
Thanks for reporting it @vstinner. This is the message I get when i try to login; 
![image](https://user-images.githubusercontent.com/47358913/70945548-7df23600-2066-11ea-8892-d4cf805d65d2.png)

**Comment by ewdurbin** [comment]
Two issues found in triaging this.

1) error emails were being suppressed due to temporary bouncing, which has now been resolved
2) it appears that something changed in the response from Google that the [oic_login.py extension is not handling](https://bitbucket.org/python/tracker-cpython/src/daf2e38b1b6a35eeb2a6e296bae2779b427182e5/extensions/oic_login.py?at=default#lines-101:102). the `result` is apparently coming back as an html string... rather than some kind of object.

**Comment by ewdurbin** [comment]
Comparing what's there to the docs for the version of pyoidc we're using it looks like there are some changes that should be considered:

https://github.com/OpenIDC/pyoidc/blob/v0.14.0/doc/examples/rp.rst#authorization-code-flow

**Comment by isidentical** [comment]
https://mail.python.org/archives/list/python-dev@python.org/message/BXWXJYB2NDDRCM7CDWL2X3IWVDW7ZE7D/

**Comment by ewdurbin** [comment]
https://bitbucket.org/python/tracker-cpython/commits/1693e3184d065f9b6eb8b5072b5003cbcafba813 appears to have resolved it using the relying party example code from https://github.com/OpenIDC/pyoidc/blob/v0.14.0/doc/examples/rp.rst#authorization-code-flow

**Comment by isidentical** [comment]
Thanks @ewdurbin, I can confirm it is working now.

**Comment by freddrake** [comment]
It's not working for me.

Using my fdrake@gmail.com address, I get the message "There is already an account for fdrake@gmail.com" when returning to bpo.

The Launchpad / Ubuntu One login works just fine.

**Comment by ewdurbin** [comment]
@freddrake it appears that your Google login was disassociated from your account 2015-04-06. was login with google working for you up until ~2 weeks ago when this issue began?

I think that what you're running into is independent of this error.

**Comment by freddrake** [comment]
No, it wasn't.  Guess it's different.
