### ISSUE TITLE
Google authentication not working for existing account without configured Google OpenID

### ISSUE THREAD

**Issue by freddrake** [python/bugs.python.org#42]
I don't see any way to set up authentication via Google on bpo at this time.  Clicking the Google link appears to be working on Google's end; it offers a "Choose an account" dialog, and records that I've used this with python.org in my security events, but bpo doesn't associate the Google authentication with my account.

Is there another way to associate a Google authentication with my bpo account?

**Comment by berkerpeksag** [comment]
I remember this was also an issue when I initially implemented (now reverted due to regressions) GitHub login support. I had to manually check existing accounts during authentication. We may need to do the same for Google login.

**Comment by stratakis** [comment]
When I try to login with google's login I get the error `There is already an account for cstratak@redhat.com`.

I cannot comment or do anything on bpo at this point.

**Comment by vstinner** [comment]
@stratakis account is: https://bugs.python.org/user23615

**Comment by vstinner** [comment]
I fixed @stratakis issue with him: we reset his password.

**Comment by freddrake** [comment]
After resetting my password, the Google login almost works and switching my "main" email address to another (keeping my gmail.com address on the list of alternates)... it no longer presents an error, but generates a new user for me instead (https://bugs.python.org/user33696).  The new user has my gmail.com address, and is associated with the Google login even after switching my address back on my real bpo account.

At any rate, the new account generated can be killed.  I didn't see a way to do that myself.

**Comment by berkerpeksag** [comment]
The fix should be deployed in an hour or so. Please let me know if you found anything weird.
