### ISSUE TITLE
Copyright should be updated.

### ISSUE THREAD

**Issue by corona10** [python/bugs.python.org#43]
AS-IS: Copyright © 1990-2019, Python Software Foundation
TO-BE: Copyright © 1990-2020, Python Software Foundation

Happy new year :)

**Comment by corona10** [comment]
@Mariatta

**Comment by tirkarthi** [comment]
cc: @ezio-melotti

**Comment by gpshead** [comment]
Copyright statements do _not_ need to have their dates updated. This is a common misconception. 
Doing that is needless churn. But you shouldn't take _my_ word on legal questions, _only_ that a PSF lawyer. @VanL

**Comment by Mariatta** [comment]
https://bitbucket.org/python/tracker-cpython/pull-requests/3/change-copyright-year/diff

**Comment by berkerpeksag** [comment]
Mariatta's PR has been merged. Closing this as 'fixed'.
