### ISSUE TITLE
Merge bugs.python.org accounts

### ISSUE THREAD

**Issue by native-api** [python/bugs.python.org#44]
I have 2 accounts linked to 2 e-mail addresses. This is rather inconvenient (especially when replying by e-mail) and I'd rather have them merged into one, ideally linked to both e-mail addresses.

Is this possible? Who should I contact on this matter?

**Comment by opensource-assist** [comment]
@native-api
The underlying roundup tracker doesn't support such a feature.
You have a few options:
- Just abandon one of the accounts.
- Open an issue on bpo itself and wait for one of the core developers to answer.(or just wait in here for them)

Even if they'd do such a thing, it requires manual tampering with the database backend of roundup.

**Comment by rouilj** [comment]
@opensource-assist merging acounts is outlined in:

   https://wiki.roundup-tracker.org/MergeUserAccounts

This allows you to merge the secondary account into the primary account and retire the
secondary account. Email coming from the secondary account address will be associated
with the primary account. (Note: roundup has always allowed multiple email addresses to be
assigned to a single account.)

This does change the data in the database using the roundup-admin cli command which uses
the roundup db api. I claim this is not manually tampering with the database backend. You
aren't using psql to do the changes but using standard roundup ORM/API to make the changes
which enforces all checks that are programmed into roundup and the tracker.

You are correct that you need a tracker admin to do the work.

-- rouilj

**Comment by berkerpeksag** [comment]
@rouilj can https://wiki.roundup-tracker.org/MergeUserAccounts be turned into a Coordinator-only custom action?

**Comment by rouilj** [comment]
Hi Berker:

In message <python/bugs.python.org/issues/44/668205217@github.com>,
Berker Peksag writes:
>@rouilj can https://wiki.roundup-tracker.org/MergeUserAccounts
>be turned into a Coordinator-only custom action?

It certainly could be. Note that it depends on the tracker. E.G. I
have a tracker with two nosy lists. So both would have to be modified.

At the moment those steps are theoretical only for the classic
tracker.  I haven't actually tried them. So we need to have somebody
verify that it works and does what is expected.

Once we have verification that the algorithm is correct it could be
added as an action.

However I have to admit this is the first time I have seen/heard
anybody request that. So it may not be worth the effort to code up a
web accessible tool to do the work.

--
				-- rouilj
John Rouillard
===========================================================================
My employers don't acknowledge my existence much less my opinions.

**Comment by berkerpeksag** [comment]
> It certainly could be.

Nice, thanks!

> However I have to admit this is the first time I have seen/heard anybody request that. So it may not be worth the effort to code up a web accessible tool to do the work.

That's true, it's definitely not a common request. I'll see what can I do about it.

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.
