### ISSUE TITLE
Replace the roundup server with a better alternative

### ISSUE THREAD

**Issue by opensource-assist** [python/bugs.python.org#45]
The current roundup server at bugs.python.org is not really satisfying.
  - It has a very old-fashioned UI design.
  - It lacks many features available in other alternatives.

It's very nice that you replace roundup with:
- GitHub issues
- [Bugzilla](https://www.bugzilla.org)(as a best open-source choice)
- [Jira Software](https://www.atlassian.com/software/jira)(the most powerful one, which is [free for open-source projects](https://www.atlassian.com/software/views/open-source-license-request))
- [YouTrack](https://www.jetbrains.com/youtrack/)(very promising, [free for open-source projects](https://www.jetbrains.com/opensource))

Roundup compared to Jira Software or YouTrack is just a joke.

**Comment by tirkarthi** [comment]
Using GitHub issues was already discussed with https://www.python.org/dev/peps/pep-0581/ . Roundup is critical for development with high amount of metadata. Moving to another issue tracker needs a substantial discussion and approval from core devs along with PEP, docs update, etc.

**Comment by Mariatta** [comment]
Decision has been made to move to GitHub Issues, which is what [PEP 581](https://www.python.org/dev/peps/pep-0581/) is about.

Roundup and b.p.o remain crucial tools for core Python development and have been maintained for so long by lots of volunteers. 
It was not necessary to describe it as "just a joke".
The PSF's [Code of Conduct](https://www.python.org/psf/conduct/) applies in this issue tracker and will be enforced.

**Comment by opensource-assist** [comment]
@Mariatta

> Decision has been made to move to GitHub Issues, which is what PEP 581 is about.

The action is the point, not the decision.
I know that GitHub lacks some functionalities that Roundup provides but Jira Software takes over all of them.

> It was not necessary to describe it as "just a joke".

Wasn't it?. Just 'take' a look at what powerful features Jira Software or YouTrack bring compared to Roundup. Get used to them and you'll understand what I meant.
I'm not affiliated with any of these services. Anyway you're not gonna pay anything for either of them. I can set up a demo instance on both of these services covering the capabilities of Roundup to show you the differences.

The core development team must buy the hardship for themselves and move to a modern infrastructure. It's 2020 now.

Just look at this <a href="https://trends.google.com/trends/explore?date=all&q=%2Fm%2F02qhzlb,%2Fm%2F0cnzfrw,Jira">google trends page</a>.

**Comment by brianquinlan** [comment]
@opensource-assist You are being (possibly unintentionally) disrespectful. In particular:
1. some core cpython developers are also Roundup developers and their efforts over the years have been invaluable and definitely not "a joke"
2. you are assuming that we aren't aware of other bug tracking solutions - we are and @Mariatta provide an evaluation of them in PEP 581.

In any case, as @Mariatta said, the decision has already been made to move to GitHub issues but, as you can imagine, it will take some time to actually make the transition (there is a draft proposal for the migration process here: https://www.python.org/dev/peps/pep-0588/).

In the future, please be more careful with your communications and check out the code of conduct here: https://www.python.org/psf/conduct/
