### ISSUE TITLE
Developer's guide menu looks strange.

### ISSUE THREAD

**Issue by corona10** [python/bugs.python.org#47]
<img width="351" alt="스크린샷 2020-01-31 오후 9 37 39" src="https://user-images.githubusercontent.com/5110323/73539953-f889e000-4471-11ea-9682-c4f18aac364e.png">

Seems to be related with https://bitbucket.org/python/tracker-cpython/pull-requests/3/change-copyright-year/diff#Lhtml/page.htmlF74

cc @Mariatta

**Comment by berkerpeksag** [comment]
Thanks for the report! It should be fixed in the next deployment.
