### ISSUE TITLE
bpo is returning statuscode 200 when there was an error

### ISSUE THREAD

**Issue by Mariatta** [python/bugs.python.org#5]
Reference issue: https://github.com/python/the-knights-who-say-ni/issues/146

If we pass in this url to bpo to check for CLA:
`https://bugs.python.org/user?@template=clacheck&github_names=`

The response text says there's an error, but with status code 200.
It would be great if b.p.o can return a proper error status code in this situation.

Thanks.

**Comment by ezio-melotti** [comment]
I've seen that error popping up in the logs and I was wondering what was triggering it :)
Should be an easy fix.

**Comment by ezio-melotti** [comment]
Done in https://hg.python.org/tracker/python-dev/rev/99cd17cb02f4 and https://hg.python.org/tracker/python-dev/rev/f40f48714e04

**Comment by Mariatta** [comment]
Thanks! I confirmed that it [works](https://github.com/python/miss-islington/pull/104#event-1684025331) now.
