### ISSUE TITLE
Account merging

### ISSUE THREAD

**Issue by isidentical** [python/bugs.python.org#50]
I have always active 2 google sessions and I sometimes accidentally choose the other one to login. Is there a way to access one account from multiple mails or merge two accounts into one.

**Comment by rouilj** [comment]
There is a way to associate your primary account with multiple email addresses. Roundup
has always had that capability.

If you have two roundup accounts, primary (the one you want to keep) and secondary (to be disabled and "merged" into the primary):

1) on the secondary account, record your email address. If your address is:
    myaddress@mydomain.com, change it to myaddress+bpodisabled@mydomain.com.
    An email addresses can only be associated with one account, so this allows you to reuse
    the secondary address as an alias in the primary account. The myaddress+bpodisabled...
    replacement will hopefully allow you to continue to get notifications on issues where your
    secondary account is on the nosy/watcher list.
    (See: https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html )

2) on the primary account account add the saved address from step 1
    (myaddress@mydomain.com) to the alternate email textbox. One address per line.

This will associate email from either gmail account with your primary roundup account.

What this will not do is set up the secondary account name as an alternate way to log into the
primary account. Roundup only supports "aliasing" for multiple source email addresses, not
multiple login names. But it looks like this is what you are looking for.

If your secondary account is assigned as a watcher on an issue, it will not be changed, but the email address change will hopefully allow you to be notified.

See https://github.com/python/bugs.python.org/issues/44 for a similar request that does replace watcher/assignments etc. and disable the second account. But it requires a tracker admin to
do the work.

-- rouilj

**Comment by isidentical** [comment]
Thanks @rouilj
