### ISSUE TITLE
I can't uninstall python

### ISSUE THREAD

**Issue by fatmafarah** [python/bugs.python.org#51]
I need to uninstall python because all of my environment is in chaos and to install it then.
I deleted python and anaconda from my programs but in the cmd when I write python to make sure it is deleted I still have this message error 

Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\Home\\python.exe'
  sys.base_prefix = 'C:\\Users\\Home\\Python38-32'
  sys.base_exec_prefix = 'C:\\Users\\Home\\Python38-32'
  sys.executable = 'C:\\Users\\Home\\python.exe'
  sys.prefix = 'C:\\Users\\Home\\Python38-32'
  sys.exec_prefix = 'C:\\Users\\Home\\Python38-32'
  sys.path = [
    'C:\\Users\\Home\\Python38-32\\python38.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\Users\\Home',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000017b4 (most recent call first):
<no Python frame>

what can I do?

**Comment by cjw296** [comment]
This issue tracker is for problems experienced using bugs.python.org, not problem you have using Python. Please try another python mailing list, such as python-list.
