### ISSUE TITLE
Can't register on site

### ISSUE THREAD

**Issue by manishprivet** [python/bugs.python.org#52]
I tried registering on site by my email address.
I got the verification email, but upon clicking on the link, it's showing errors.
A screenshot is attached below.

![bpo error](https://user-images.githubusercontent.com/54291836/86745203-d0715f00-c057-11ea-9c67-3aa4e094bdc0.jpg)

**Comment by rouilj** [comment]
Hello Manish:

This error is reported when creating a new user with an invalid homepage url.
It must be an http or https url.

When you registered, what did you fill in as your homepage url?
It is the line right above the required email address field in the registration form.

-- rouilj

**Comment by rouilj** [comment]
Ping Manish.

**Comment by manishprivet** [comment]
Yes I did check it, and tried registering again, but the error appeared. I finally settled with signing in by OAuth.
