### ISSUE TITLE
numpy library not working with Python38 Interpreter

### ISSUE THREAD

**Issue by darkscarletspeedster** [python/bugs.python.org#53]
The numpy imports is not recognized using Python Interpreter 38(64 bit) but works fine for 38-32(32 bit), my system 64-bit system, it gives error: os.add_dll_directory(extra_dll_dir)
AttributeError: module 'os' has no attribute 'add_dll_directory'

**Comment by darkscarletspeedster** [comment]
I installed a 64-bit installer that solved it for me so closing this issue

**Comment by aeros** [comment]
@darkscarletspeedster For future reference, this repo's issue tracker is for reporting bugs for the *site* bugs.python.org. For actual bugs related to CPython, please file a bug report on bugs.python.org.
