### ISSUE TITLE
Not receiving any email

### ISSUE THREAD

**Issue by merwok** [python/bugs.python.org#56]
Hello!  I noticed this week that I don’t get email from bpo.

My profile is https://bugs.python.org/user7641

**Comment by iritkatriel** [comment]
Me too. I stopped getting updates.

**Comment by merwok** [comment]
It’s been better recently for me.

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.
