### ISSUE TITLE
GitHub OpenID email link error links to wrong settings page

### ISSUE THREAD

**Issue by msuozzo** [python/bugs.python.org#57]
*Problem*: When I try to add my GitHub OpenID account to my existing bpo account, I see a banner that reads:

> Your email address couldn't be fetched from your GitHub profile. Please make it public at https://github.com/settings/emails.

I have multiple emails in my GH account but on the Profile page, the `Keep my email addresses private` is unchecked and both of my emails have the indicator `Visible in emails`.

I believe this may be preventing me from showing up as having signed the CLA as the `check-python-cla` app shows "msuozzo does not have bpo account".

**Comment by berkerpeksag** [comment]
I think you also need to set your public email at https://github.com/settings/profile:

![image](https://user-images.githubusercontent.com/26338/98040051-58aa1a00-1e28-11eb-8106-6363f156e44c.png)

**Comment by berkerpeksag** [comment]
Also, feel free to suggest alternative wording for that message. I'd be happy to make it more clear. Thank you!

**Comment by msuozzo** [comment]
That worked! Thanks so much!

Would you be able to add the link to the main profile config since that also needs to be changed?

Maybe referencing `Public Email` at github.com/settings/profile instead of the settings/email one?

**Comment by berkerpeksag** [comment]
Yes, that's definitely a good idea! The message comes from https://github.com/psf/bpo-tracker-cpython/blob/00d4e3f28c88811ed948796bf42825bc7f662bf2/extensions/oic_login.py#L316-L317. I'd be happy to review and merge a PR if you have the time.

**Comment by msuozzo** [comment]
https://github.com/psf/bpo-tracker-cpython/pull/1

**Comment by berkerpeksag** [comment]
Thank you!
