### ISSUE TITLE
High cpu usage with asyncio streams

### ISSUE THREAD

**Issue by romikforest** [python/bugs.python.org#58]
Hi. I have high cpu usage using asyncio streams and connection pool.
Here is a simplified example https://github.com/romikforest/asyncio_streams_high_cpu_usage2

Thanks a lot in advance if you can take a look.

**Comment by berkerpeksag** [comment]
Thank you for providing a reproducer, but unfortunately this isn't the correct place to report such issues. This is a meta tracker for bugs.python.org. You need to report this to https://bugs.python.org/.

**Comment by terryjreedy** [comment]
Post to python-list for discussion first.  The reproducer involves multiple 3rd party packages, and a reproducer for bpo should only require stdlib modules.
