### ISSUE TITLE
Don't send email when someone is added/removed from nosy list

### ISSUE THREAD

**Issue by Mariatta** [python/bugs.python.org#6]
Personally I find it just noise..
If such emails can be disabled, it would be appreciated.

I saw it requested since 2012 in the upstream roundup.
http://issues.roundup-tracker.org/issue2550742

If it can't get done in upstream, I hope bpo can support this.
Thanks.

**Comment by rouilj** [comment]
Sending email is part of the tracker config/code and a not a core feature of roundup. The decision to send/not send email is coded in (the classic tracker's) nosyreactor.py. Also the standard nosyreactor.py IIRC only sends email if there is a message. An email just for  change in the nosy list sounds like there is a custom reactor sending it.

**Comment by berkerpeksag** [comment]
I think this can be implemented in https://github.com/psf/bpo-tracker-cpython/blob/master/detectors/sendmail.py I'll see what can I do.

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.
