### ISSUE TITLE
Not receiving email from the bug tracker

### ISSUE THREAD

**Issue by iritkatriel** [python/bugs.python.org#62]
For about a week I am getting no email about updates to issues I nosy. I added a second email address to my account but this didn't help. I don't see the emails in either spam folder.

**Comment by iritkatriel** [comment]
I changed the email address and it works (a @gmail.com address works, a @yahoo.com one stopped working).

**Comment by iritkatriel** [comment]
For anyone else having issues, I found it useful to save a query showing "last actor" on issues I'm following:

https://bugs.python.org/issue?@columns=title,id,activity,actor,status&@sort=-activity&@filter=nosy&@pagesize=50&@startwith=0&nosy=34626&@dispname=My%20Updates

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.
