### ISSUE TITLE
Can't log into bugs.p.o with Github account due to non-ASCII character in name

### ISSUE THREAD

**Issue by asedeno** [python/bugs.python.org#63]
When trying to log in, my name `Alejandro R. Sedeño` results in:
`'ascii' codec can't encode character u'\xf1' in position 17: ordinal not in range(128)`

That's not great. There's lots of good characters in Unicode besides what's in ASCII.
Also, `u'\xf1'` suggests bugs.p.o is still using python2? I'm told that's EOL.

**Comment by pawamoy** [comment]
Same here because of the é in my name :sweat_smile::

![asciicodec](https://user-images.githubusercontent.com/3999221/132847666-08c90b36-4a17-42b2-be8b-ba033fe0ac91.png)

**Comment by terryjreedy** [comment]
> u'\xf1' suggests bugs.p.o is still using python2?

After being initially removed, 'u' prefix was added back to 3.x aid porting from 2.x.  I believe it will be removed some time.

bpo is scheduled to be replaced rather than updated.

**Comment by asedeno** [comment]
> > u'\xf1' suggests bugs.p.o is still using python2?
> 
> After being initially removed, 'u' prefix was added back to 3.x aid porting from 2.x. I believe it will be removed some time.

You can use `u'string'` in python 3.x since it was added back, sure, and that was a good move, but it is not used in the repr of `str` in py3. The `u'\xf1'` in the error message is a giveaway that bpo runs on py2.

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 17: ordinal not in range(128)` is how python2 says it.
`UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 17: ordinal not in range(128)` is how python3 says it.

> bpo is scheduled to be replaced rather than updated.

Cool, maybe then I can log in and use it. :-)

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.

cc @rouilj
