### ISSUE TITLE
Using '==' outside if statement

### ISSUE THREAD

**Issue by TorChrish** [python/bugs.python.org#69]
By misstake I made a variable assignment using two equal signs, like this code:
```python
flag == True
```
This error was not notified by the syntax check, but totally ignored during execution of the program. 
It happened several times as my keyboard is very sensitive.
The Python version:
Python 3.10.12
Running Ubuntu 22.04 on an old  64-bit cpu laptop.

Surrounding code was like this 👍 
```python
					pix = pya.pixel(x, y)
#					print("(" + str(x) + "," + str(y) + ")  " + str(pix))
					if pix[0] == 253 and pix[1] == 235 and pix[2] == 27:
						flag == True
#						print("line: " + str(tt.getlinenbr()) + " " + str(flag)) 
						break
#				print("line: " + str(tt.getlinenbr()) + " " + str(flag)) 
				if flag:
					break
```

 Hope you can use this information
Tor chris

**Comment by Mariatta** [comment]
Thanks for posting, but this ticket seems not relevant to the repository.
Closing.

**Comment by terryjreedy** [comment]
Please ask questions about using Python on help forums such as https://discuss.python.org/c/help/7.
