### ISSUE TITLE
Support logging in with GitHub

### ISSUE THREAD

**Issue by Mariatta** [python/bugs.python.org#7]
It would be great if we can login to bpo using GitHub.

Thanks.

**Comment by ammaraskar** [comment]
# Setup Instructions

Generate a set of github oauth credentials here:
https://github.com/settings/applications/new

Set the authorization callback url to be:
https://bugs.python.org/index?@action=oic_authresp&provider=Github

Insert the client_id and client_secret into the database:

```sql
INSERT INTO _oic_registration 
  (_issuer, _client_id, _client_secret, id) 
  VALUES ('https://github.com/settings/developers', 'xx', 'xx', x);
```

Patch for http://hg.python.org/tracker/python-dev: https://gist.github.com/ammaraskar/e259bc7d50df354e796e3c0d61137b10

**Comment by ammaraskar** [comment]
@ezio-melotti Antoine said you'd be the right person to talk to about getting this merged. Lemme know if you want the patch in some specific way or another.

**Comment by ewdurbin** [comment]
A GitHub application managed by the python organization has been created with the name `bugs.python.org` and configured as directed above.

**Comment by Mariatta** [comment]
I still have not figured out how to register/login to bpo using GitHub account 😟
Has the patch been merged? @ammaraskar @ezio-melotti?

**Comment by ammaraskar** [comment]
@berkerpeksag might also be able to answer, I think they mentioned this was disabled for some reason.

**Comment by berkerpeksag** [comment]
It wasn't fully deployed for end users. By default, GitHub API doesn't include email addresses of users even if we set the OAuth scope correctly (users need to make their email address public on GitHub or we need to make a request to another endpoint in order to get their email address)

I'm not going to work on it until I get a response from Barry regarding PEP 595.

**Comment by berkerpeksag** [comment]
I've just re-pushed the patch with some modifications. I've already tested both Google and GitHub login supports locally. It should detect and associate existing bugs.python.org accounts with the same email address.

The only limitation is that the email address must be set to public in user's email settings at GitHub.
