### ISSUE TITLE
Report which CPython version a PR was merged for

### ISSUE THREAD

**Issue by ncoghlan** [python/bugs.python.org#9]
At least in theory, there's enough info in the GitHub commit reference for b.p.o to figure out which version a merged PR will end up being released in.

Specifically:

- there's already a PR reference added to the issue by the GitHub bots
- the squashed-and-merged commit is linked back to the issue in a comment
- the GitHub API also exposes the landed commit hash in the `merged_commit_hash` field: https://developer.github.com/v3/pulls/#response-1
- given a commit hash, you can work out  which release that's going to land in by looking at https://github.com/python/cpython/blob/master/Include/patchlevel.h (You could also work it out by looking at the git history and the git tags, but I expect reading the patch level header directly will be simpler)

Given that information, it seems like it would then be possible to update the PR listing to display "Merged for X.Y.Z" rather than just displaying "Merged" as it does now.

For this to be completely practical, we may need to use a dynamic key-value store to cache the info somewhere, but that's a useful capability to have for multiple reasons (not just for b.p.o), and @ewdurbin may be able to arrange for something that's usable across PSF-provided infrastructure services in general (including the other GH bots, not just in b.p.o).

**Comment by ezio-melotti** [comment]
We now migrated to [GitHub](https://github.com/python/cpython/issues), so this can be closed.
